config/routes.rb
Wunderkind::Application.routes.draw do

  devise_for :users
  devise_for :customers,
             controllers: {omniauth_callbacks: 'authentications', registrations: 'devise/registrations' }

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  scope '(:locale)' do
    resources :static_pages
    resources :categories
    resources :sub_categories
    resources :products
    resources :brands
    resources :line_items
    resources :orders
    resources :carts
    resources :authentications do
      collection do
        post 'pay'
        get 'return_from_pay'
        get 'callback'
      end
    end
  end

  root 'authentications#home'

end

app/models/cart.rb
class Cart < ActiveRecord::Base
  has_many :line_items, dependent: :destroy

  def add_product(product_id, quantity, c)
    current_item = line_items.find_by(product_id: product_id)
    if current_item
      if c
        current_item.quantity = quantity.to_i
      else
        current_item.quantity += quantity.to_i
      end
    else
      current_item = line_items.build(product_id: product_id, quantity: quantity.to_i)
    end

    current_item
  end

  def total_price
    line_items.to_a.sum { |item| item.total_price }
  end

  def items_quantity
    line_items.to_a.sum { |item| item.quantity }
  end

end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:show, :edit, :update, :destroy]

  rescue_from ActiveRecord::RecordNotFound, with: :invalid_cart
  def index
    @carts = Cart.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @carts }
    end
  end

  def show
    begin
      if :authenticate_customer!
        @cart = Cart.find(params[:id])
        if @cart.total_price == 0
          redirect_to root_url
          flash[:error] = t('carts.show.cart_empty')
        end
      else
        redirect_to root_url
      end
      rescue ActiveRecord::RecordNotFound
      redirect_to root_url
    end
  end

  def new
    @cart = Cart.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @cart }
    end
  end

  def edit
    @cart = Cart.find(params[:id])
  end

  def create
    @cart = Cart.new(params[:cart])

    respond_to do |format|
      if @cart.save
        format.html { redirect_to @cart, notice: 'Cart was successfully created.' }
        format.json { render json: @cart, status: :created, location: @cart }
      else
        format.html { render action: "new" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @cart = Cart.find(params[:id])

    respond_to do |format|
      if @cart.update_attributes(params[:cart])
        format.html { redirect_to @cart }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @cart.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @cart.destroy if @cart.id == session[:cart_id]
    session[:cart_id] = nil
    respond_to do |format|
      format.html { redirect_to products_url }
      format.js
      format.json { head :no_content }
    end
  end

  private

    def invalid_cart
      logger.error "Attempt to access invalid cart #{params[:id]}"
      redirect_to products_path, notice: 'Invalid Cart'
    end
end

app/helpers/carts_helper.rb
module CartsHelper

end

app/views/carts/_cart.html.erb
<% item = t('products.show.items') %>
<% vertical_bar = t('products.show.symbol') %>
<% cart_id = cart_path(cart.id) %>

<div class="w23per float-right" id="top-cart">
  <%= link_to image_tag('top-cart-icon.png', class: 'float-left', alt: 'კალათა'), cart_id %>
  <div>
    <h3><%= link_to t('products.show.your_cart'), cart_id %></h3>
    <div>
    <% if get_loc == 'en' %>

        <%= link_to pluralize(@cart.items_quantity, item), cart_id %>
        <%= vertical_bar %>

    <% else %>
          <%= link_to "#{@cart.items_quantity} #{item}", cart_id %>
          <%= vertical_bar %>
    <% end %>
    <%= link_to "#{sprintf('%.2f', @cart.total_price)} #{t('products.show.currency')}", cart_id %></div>
  </div>
</div>

app/views/carts/show.html.erb
<% if @cart.total_price != 0 %>
<section class="mt10px w76per float-right" id="main-section">
  <section class="full-width float-left mt10px">
    <h2 class="full-width float-left mb10px fs18px fbold">
     <%= t('carts.show.product_list') %>
    </h2>
    <table class="perprodStyle cartStyle" cellspacing="0" cellpadding="0">
      <tbody class="full-width">
      <tr class="full-width" style="text-align: center;">
        <th style="text-align: left;"><%= t('carts.show.image') %></th>
        <th><%= t('carts.show.title') %></th>
        <th><%= t('carts.show.quantity') %></th>
        <th><%= t('carts.show.per_price') %></th>
        <th><%= t('carts.show.total_price') %></th>
      </tr>
      <%= render(@cart.line_items) %>
      </tbody>
    </table>
    <div style="padding: 30px; background: #e7e7e7; text-align: right; clear: both; font-size: 24px;">
      <%= sprintf('%.2f', @cart.total_price) %>&nbsp;<%= t('products.show.currency') %>
    </div>
    <div class="full-width float-left mt14px">
      <%= link_to t('carts.show.back'), '', class: 'standardButtonStyle' %>
      <%= link_to t('carts.show.empty_cart'), @cart, method: :delete, data: { confirm: t('carts.show.confirm') }, class: 'standardButtonStyle', style: 'margin-left: 14px' %>
      <%= link_to t('carts.show.buy_product'), new_order_path, method: :get, class: 'standardButtonStyle', style: 'float: right' %>
    </div>
  </section>
</section>
<% else %>

<% end %>