config/routes.rb
Wunderkind::Application.routes.draw do

  devise_for :users
  devise_for :customers,
             controllers: {omniauth_callbacks: 'authentications', registrations: 'devise/registrations' }

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  scope '(:locale)' do
    resources :static_pages
    resources :categories
    resources :sub_categories
    resources :products
    resources :brands
    resources :line_items
    resources :orders
    resources :carts
    resources :authentications do
      collection do
        post 'pay'
        get 'return_from_pay'
        get 'callback'
      end
    end
  end

  root 'authentications#home'

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :sub_categories, dependent: :destroy
  accepts_nested_attributes_for :sub_categories, :allow_destroy => true
  validates :title_ge, presence: true
  validates :title_en, presence: true

  rails_admin do
    label I18n.t('admin.category.menu_name')
    label_plural I18n.t('admin.category.menu_name')
    list do
      field :id
      field :title_ge do
        label I18n.t('admin.category.title_ge')
      end
      field :title_en do
        label I18n.t('admin.category.title_en')
      end
    end

    show do
      field :id
      field :title_ge do
        label I18n.t('admin.category.title_ge')
      end
      field :title_en do
        label I18n.t('admin.category.title_en')
      end
    end

    edit do
      field :title_ge do
        label I18n.t('admin.category.title_ge')
      end
      field :title_en do
        label I18n.t('admin.category.title_en')
      end
    end
  end

  def category_fields
    "#{self.title_ge}"
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  attr_accessor :categories

  def index
    @categories = Category.all
  end

  def show
    @category = Category.find_by_id(params[:id])
    @subs = SubCategory.where(category_id: @category.id)
    #@prod = Product.where(sub_category_id: [@subs.ids])
    #@brands = Brand.joins('LEFT JOIN products ON products.brand_id = brands.id').group('brands.id')
    @brands = Product.joins(:sub_category, :brand).select('brands.id, brands.title_ge, brands.title_en, sub_categories.id as sub_id, COUNT(*) as prod_quantity')
              .group('brands.id')


  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
  def cat_product_list(pid)
    Product
    .where('brand_id = ? AND quantity > 0', params[:id]).where('prefix_id = ?', pid)
    .select('*')
  end

end

app/views/categories/show.html.erb
<section class="mt10px w76per float-right" id="main-section">
  <section class="full-width float-left mt10px">
    <h2 class="full-width float-left mb10px fs16px fbold">
      <%= @category["title_#{get_loc}"] %>
    </h2>

    <div class="full-width float-left mt10px">
    <% @subs.each do |sub| %>
    <div class="w30per paddinglr float-left mb10px mt14px">
        <h1 class="full-width color-blue fs18px mb10px float-left"><%= sub["title_#{get_loc}"]%></h1>
        <%= image_tag sub.sub_img.url(:medium), class: 'full-width mb10px float-left' %>
        <% @brands.each do |b| %>
          <div class="full-width float-left">
            <% if sub.id == b.sub_id %>
            <%= link_to "#{b["title_#{get_loc}"]} #{b.prod_quantity}", brand_path(b.id), class: 'color-gray fs14px borderbGray marpadstyle' %>
            <% end %>
          </div>
        <% end %>
     </div>
    <% end %>
    </div>
  </section>
</section>