config/routes.rb
Wunderkind::Application.routes.draw do

  devise_for :users
  devise_for :customers,
             controllers: {omniauth_callbacks: 'authentications', registrations: 'devise/registrations' }

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  scope '(:locale)' do
    resources :static_pages
    resources :categories
    resources :sub_categories
    resources :products
    resources :brands
    resources :line_items
    resources :orders
    resources :carts
    resources :authentications do
      collection do
        post 'pay'
        get 'return_from_pay'
        get 'callback'
      end
    end
  end

  root 'authentications#home'

end

app/models/line_item.rb
class LineItem < ActiveRecord::Base
  belongs_to :product
  belongs_to :cart


  def total_price
    if product.discount == 0
      product.price * quantity
    else
      product.discount * quantity
    end
  end

  def per_item_price
    if product.discount == 0
      product.price
    else
      product.discount
    end
  end

end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  include CurrentCart
  before_action :set_cart, only: [:create]
  #before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  def show
    @line_item = LineItem.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @line_item }
    end
  end

  def create
    product = Product.find(params[:product_id])
    quantity = params[:quantity]
    c = params[:c]
    @line_item = @cart.add_product(product.id, quantity, c) if product.quantity > 0

    respond_to do |format|
      if @line_item.save
        @line_item.destroy if @line_item.quantity == 0
        format.html { redirect_to @line_item.cart, notice: t('line_items.create.line_item_created') }
        format.js { @c = c, flash[:success] = t('line_items.create.line_item_created') }
        format.json { render json: @cart, status: :created, location: @line_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end


  def new; end
  def edit; end
  def update; end


  def destroy
    @line_item = LineItem.find(params[:id])
    @cart = current_cart
    begin
      @line_item.destroy
      flash[:notice] = t('products.show.line_item_removed')
    rescue Exception => e
      flash[:notice] = e.message
    end

    respond_to do |format|
      format.html { redirect_to cart_path(@cart) }
      format.json { head :no_content }
    end

  end


  def update_quantity; end

  def line_item_params
    params.require(:line_item).permit(:product_id)
  end

end

app/helpers/line_items_helper.rb
module LineItemsHelper
  def one_product_image(pid)
    Image.where('product_id = ?', pid).limit(1)
  end
end

app/views/line_items/_line_item.html.erb
<tr class="full-width">
  <td style="text-align: left;">
    <% one_product_image(line_item.product_id).each do |img| %>
        <%= link_to image_tag(img.product_img, style: 'width: 41px'), class: 'all-inherit' %>
    <% end %>
  </td>
  <td>
    <%= link_to line_item.product["title_#{get_loc}"], product_path(line_item.product_id), class: 'all-inherit' %>
  </td>
  <%= form_tag line_items_path(product_id: line_item.product_id), remote: true do %>
  <td style="width: 178px; text-align: center;">
    <span class="cartAddRem">
      <button class="minus">-</button>
        <%= text_field_tag 'quantity', line_item.quantity, size: 1, class: 'quantity' %>
        <%= hidden_field_tag 'c', '1'  %>
      <button class="plus">+</button>
      <span><%= t('layouts.quantity') %></span>
    </span>
    <% if params[:controller] == 'carts' %>
        <%= submit_tag '', class: 'cartdelred' %>
        <%= link_to '',
                    {:action => :destroy, :controller => 'line_items', :id => line_item.id },
                    method: :delete,  class: 'cartdelred' %>
    <% else %>
        <%= submit_tag t('products.show.add_to_cart') %>
    <% end %>
  </td>
  <% end %>
  <td><%= sprintf('%.2f', line_item.per_item_price) %>&nbsp;<%= t('products.show.currency') %></td>
  <td><%= sprintf('%.2f', line_item.total_price) %>&nbsp;<%= t('products.show.currency') %></td>
</tr>

app/views/line_items/create.js.erb
$('#cart').html("<%= escape_javascript render(@cart) %>");
<% if @c %>
    window.location.reload();
<% end %>