config/routes.rb
Wunderkind::Application.routes.draw do

  devise_for :users
  devise_for :customers,
             controllers: {omniauth_callbacks: 'authentications', registrations: 'devise/registrations' }

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  scope '(:locale)' do
    resources :static_pages
    resources :categories
    resources :sub_categories
    resources :products
    resources :brands
    resources :line_items
    resources :orders
    resources :carts
    resources :authentications do
      collection do
        post 'pay'
        get 'return_from_pay'
        get 'callback'
      end
    end
  end

  root 'authentications#home'

end

app/views/layouts/_footer.html.erb
<footer class="full-width float-left mt14px" id="footer1">
  <section class="full-width float-left" style="height: 50px;">
  </section>

  <section class="full-width float-left mt6px p" id="footer2">
    <div class="full-wrapp">
      <div class="full-width float-left">
        <ul class="mt14px mb10px nino float-left inline-items fs18px color-black">
          <li><a href="#">სავაადმყოფო</a></li>
          <li><a href="#">პედიატრი</a></li>
          <li><a href="#">ჭოჭინა</a></li>
          <li><a href="#">პედიატრი</a></li>
          <li><a href="#">ჭოჭინა</a></li>
          <li><a href="#">პედიატრი</a></li>
          <li><a href="#">გრდემლი</a></li>
        </ul>
        <ul class="mt10px mb10px float-right inline-items">
          <li><%= link_to image_tag('fb-b.png') %></li>
          <li><%= link_to image_tag('yb-b.png') %></li>
          <li><%= link_to image_tag('gg-b.png') %></li>
        </ul>
      </div>
    </div>
    <div class="full-wrapp">
      <div class="full-width float-left">
        <div class="float-left fs13px color-black ml10px mt14px mb6px">
          &copy; Arr Rights Reserved
        </div>

        <div class="float-right fs13px color-black ml10px mt14px mb6px">
          Created by: <a href="#" class="fs14px fbold" style="color: #000;">Stand<span class="color-blue" style="color: #0033cc;">ART</span></a>
        </div>
        <%# debug(params) if Rails.env.development? %>
      </div>
    </div>
  </section>
</footer>
</section>

app/views/layouts/_header.html.erb
<header  class="full-width">
  <div class="full-width" id="header-top-bar">
    <div class="full-wrapp">
      <ul class="inline-items float-left">
        <% if customer_signed_in? %>
            <li><%= t('layouts.balance') %>: <%= sprintf('%.2f', current_amount) %> <%= t('products.show.balance') %></li>
        <% else %>
            <li><%= link_to t('layouts.sign_in'), new_customer_session_path %></li>
            <li><%= link_to t('layouts.sign_up'), new_customer_registration_path %></li>
            <li><%= link_to image_tag('fblogin.png', class: 'facebook_button'), customer_omniauth_authorize_path(:facebook) %></li>
        <% end %>
      </ul>
      <ul class="inline-items float-right">
        <% if customer_signed_in? %>
            <li style="position: relative;"><a href="#" id="top-who-is">
              <%= current_customer.first_name %> <%= current_customer.last_name %>
            </a>
              <ul class="balanceDrop">
                <li><%= link_to t('layouts.edit_profile'), edit_customer_registration_path %></li>
                <li><%= link_to t('layouts.my_orders'), orders_path %></li>
                <li><%= link_to t('layouts.my_balance'), authentications_path %></li>
                <li><%= link_to t('layouts.logout'), destroy_customer_session_path, method: :delete %></li>
              </ul>
            </li>
        <% end %>
      </ul>
    </div>
  </div>
  <div class="full-wrapp" id="header-container">
    <h1 class="w33per float-left" id="logo"><%= link_to image_tag('logo.png', class: 'full-width', alt: 'WunderKind.Ge'), '/' %></h1>

    <div class="w36per float-left" id="top-navsearch">
      <ul class="full-width inline-items float-left" id="top-stat-pages">
        <li><%= link_to t('layouts.about_us'), '#' %></li>
        <li><%= link_to t('layouts.service'), '#' %></li>
        <li><%= link_to t('layouts.contact'), '#' %></li>
      </ul>

      <ul class="w21per float-left inline-items" id="top-soc-pages">
        <li><a href="#"><%= link_to image_tag('top-fb-icon.png', alt: 'facebook page') %></a></li>
        <li><a href="#"><%= link_to image_tag('top-vk-icon.png', alt: 'vk page') %></a></li>
        <li><a href="#"><%= link_to image_tag('top-tw-icon.png', alt: 'tweeter page') %></a></li>
      </ul>

      <div class="w74per float-right" id="top-search-bar">
        <%= form_tag(products_path, :method => 'get', id: 'search-form') do %>
            <%= text_field_tag :search, params[:search], placeholder: t('layouts.search') %>
            <%= submit_tag '', :name => nil %>
        <% end %>
      </div>
    </div>

    <div id="cart">
      <%= render @cart %>
    </div>

    <ul class="full-width" id="header-nav">
      <% categories[:cat].each do |cat| %>
          <li><%= link_to cat["title_#{get_loc}"], category_path(cat.id) %>
          <ul>
            <% categories[:sub].where(category_id: cat.id).each do |sub| %>
                <li><%= link_to sub["title_#{get_loc}"], sub_category_path(sub.id) %></li>
            <% end %>
          </ul>
          </li>
      <% end %>
    </ul>
  </div>
</header>

app/views/layouts/_left_column.erb
<%= form_tag(products_path, :method => 'get', id: 'sidebar', class: 'mt10px gray-bg w23per blue-border border-8-radius float-left') do %>
<h2 class="mt10px ml5per mb10px w90per float-left fs16px color-blue"><%= t('layouts.category_list') %></h2>
<div class="w90per float-left mr1perc color-gray borderbGray ml5per">
  <%= collection_radio_buttons(:sub_category, :id, SubCategory.all, :id, :title_ge) do |b| %>
      <% unless params[:sub_category].nil?  %>
      <% c = 'checked' if (params[:sub_category][:id].to_i == b.value)  %>
      <% end %>
        <%= b.label(:'data-value' => b.value, class: 'fs13px full-width float-left mb10px') { b.radio_button(checked: c) + "\t#{b.text}" } %>
  <% end %>
</div>

<h2 class="mt10px ml5per mb10px w90per float-left fs16px color-blue"><%= t('layouts.brand_list') %></h2>
<div class="w90per float-left mr1perc color-gray borderbGray ml5per">
    <%= collection_check_boxes(:brand, :id, Brand.all, :id, :title_ge) do |b| %>
        <%= b.label(:'data-value' => b.value, class: 'fs13px full-width float-left mb10px') { b.check_box + "\t#{b.text}" } %><br />
    <% end %>
</div>

<h2 class="mt10px ml5per mb10px w90per float-left fs16px color-blue"><%= t('layouts.sex_list') %></h2>
<div class="w90per float-left mr1perc color-gray borderbGray ml5per">
    <%= collection_check_boxes(:sex, :id, Sex.all, :id, :sex_ge) do |b| %>
        <%= b.label(:'data-value' => b.value, class: 'fs13px full-width float-left mb10px') { b.check_box + "\t#{b.text}" } %><br />
    <% end %>
</div>

<h2 class="mt10px ml5per mb10px w90per float-left fs16px color-blue"><%= t('layouts.age_list') %></h2>
<div class="w90per float-left mr1perc color-gray borderbGray ml5per">
    <%= collection_check_boxes(:age, :id, Age.all, :id, :age_ge) do |b| %>
        <%= b.label(:'data-value' => b.value, class: 'fs13px full-width float-left mb10px') { b.check_box + "\t#{b.text}" } %><br />
    <% end %>
</div>

<div class="w90per float-left mr1perc color-gray borderbGray ml5per" style="padding-bottom: 20px">
    <h2 class="mt10px mb10px full-width float-left fs16px color-blue"><%= t('layouts.price_list') %></h2>
    <div data-min="<%= Product.minimum('price') %>" data-max="<%= Product.maximum('price') %>" class="green-range-bar float-left w90per mw5per mt10px mb10px">
        <span class="from"></span>
        <span class="to"></span>
        <span class="min-value fs14px color-gray"></span>
        <span class="max-value fs14px color-gray"></span>
        <%= hidden_field_tag 'price_min', Product.minimum('price') %>
        <%= hidden_field_tag 'price_max', Product.maximum('price') %>
        <%= hidden_field_tag 'f', 'f' %>
    </div>
</div>
    <div class="w90per float-left mr1perc color-gray ml5per" style="margin-top: 20px;">
        <%= submit_tag 'ძიება', class: 'standardButtonStyle full-width', style: 'display: block; float: none; padding-left: 0; padding-right: 0;' %>
    </div>
<% end %>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= meta_info.meta_title %> | <%= full_title(yield(:title)) %></title>
  <meta name="description" content="<%= meta_info.meta_description %>">
  <meta name="keywords" content="<%= meta_info.meta_keywords %>">
  <meta charset="UTF-8">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
</head>
<body class="<%= controller.controller_name %>">
    <%= render 'layouts/header', categories: menu_items %>
    <section class="full-wrapp">
      <%= render 'layouts/left_column' %>
        <%= yield %>
    </section>
    <%= render 'layouts/footer' %>
    <% flash.each do |key, value| %>
    <div class="alerts alert-<%= key %>">
      <div class="full-wrapp"><%= value %></div>
    </div>
    <% end %>
</body>
</html>